export const LEFT = 'LEFT';
export const RIGHT = 'RIGHT';
export const BAIT = 'Б';
export const GAME_END = 1000;
export const WINNER = 'WIN!!!';
export const DEFAULT_LEFT_NAME = 'Мы';
export const DEFAULT_RIGHT_NAME = 'Они';
export const CHANGE_NAME_TEXT_TITLE = 'Хотите сменить имя?';
export const CHANGE_NAME_TEXT_LABEL = 'Введите имя';